// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/demogoo/wirego/internal/config"
	"github.com/demogoo/wirego/internal/handlers"
	"github.com/demogoo/wirego/internal/server"
	"github.com/demogoo/wirego/internal/services"
	"github.com/demogoo/wirego/internal/storage"
)

// Injectors from container.go:

func CreateServer() *server.Server {
	configConfig := config.NewConfig()
	mongoDBConn := storage.NewMongoDBConn(configConfig)
	itemService := services.NewItemService(mongoDBConn)
	itemHandler := handlers.NewItemHandler(itemService)
	cacheConn := storage.NewCacheConn(configConfig)
	orderService := services.NewOrderService(cacheConn)
	orderHandler := handlers.NewOrderHandler(orderService)
	dbConn := storage.NewDBConn(configConfig)
	memberService := services.NewMemberService(dbConn)
	memberHandler := handlers.NewMemberHandler(memberService)
	serverServer := server.NewServer(configConfig, itemHandler, orderHandler, memberHandler)
	return serverServer
}
